import { getEntityPlaceholderImage } from "@/lib/entity-placeholder";

export interface CuratedItemTemplate {
  id: string;
  category: "weapons" | "potions" | "armor" | "gear" | "treasure";
  title: string;
  description: string;
  subtitle: string;
  rarity?: string;
  value?: string;
  meta?: string[];
  featured?: boolean;
  imageUrl: string;
  searchText?: string;
}

export interface CuratedNpcTemplate {
  id: string;
  name: string;
  race: string;
  npcClass: string;
  alignment: string;
  relationship: "ally" | "enemy" | "neutral" | "patron" | "rival";
  faction?: string;
  locationName?: string;
  personality: string;
  appearance: string;
  voice: string;
  description: string;
  notes: string;
  isEnemy?: boolean;
  cr?: string;
  featured?: boolean;
  imageUrl: string;
}

function itemImage(name: string) {
  return getEntityPlaceholderImage("item", name);
}

function npcImage(name: string) {
  return getEntityPlaceholderImage("npc", name);
}

export const CURATED_ITEM_TEMPLATES: CuratedItemTemplate[] = [
  {
    id: "weapon-blackrazor",
    category: "weapons",
    title: "Blackrazor",
    description: "A soul-hungry legendary greatsword suited to a grim arc, cursed vault, or fallen champion.",
    subtitle: "Iconic weapon",
    rarity: "legendary",
    value: "Artifact",
    meta: ["Greatsword", "Sentient", "Soul eater"],
    featured: true,
    imageUrl: itemImage("Blackrazor"),
    searchText: "greatsword artifact famous weapon legendary",
  },
  {
    id: "weapon-wave",
    category: "weapons",
    title: "Wave",
    description: "A tide-calling trident fit for sea kings, drowned temples, leviathan hunts, and storm cult relics.",
    subtitle: "Iconic weapon",
    rarity: "legendary",
    value: "Artifact",
    meta: ["Trident", "Ocean", "Storm relic"],
    featured: true,
    imageUrl: itemImage("Wave"),
  },
  {
    id: "weapon-whelm",
    category: "weapons",
    title: "Whelm",
    description: "A famous dwarven warhammer ideal for lost halls, heirloom quests, or reclaiming a mountain throne.",
    subtitle: "Iconic weapon",
    rarity: "legendary",
    value: "Artifact",
    meta: ["Warhammer", "Dwarven", "Heirloom"],
    featured: true,
    imageUrl: itemImage("Whelm"),
  },
  {
    id: "weapon-sunsword",
    category: "weapons",
    title: "Sunsword",
    description: "A radiant blade that feels perfect for vampire hunts, fallen dynasties, and holy vengeance.",
    subtitle: "Named relic",
    rarity: "legendary",
    value: "Priceless",
    meta: ["Radiant", "Undead slayer", "Longsword"],
    featured: true,
    imageUrl: itemImage("Sunsword"),
  },
  {
    id: "weapon-azuredge",
    category: "weapons",
    title: "Azuredge",
    description: "A noble city's returning axe, ideal for a champion of law, guard captain, or frontier lord.",
    subtitle: "Named relic",
    rarity: "very_rare",
    value: "6,000 gp",
    meta: ["Battleaxe", "Returning", "City relic"],
    imageUrl: itemImage("Azuredge"),
  },
  {
    id: "weapon-twinkle",
    category: "weapons",
    title: "Twinkle",
    description: "A graceful enchanted scimitar suited to drow heroes, duelists, or moonlit infiltrators.",
    subtitle: "Named relic",
    rarity: "very_rare",
    value: "5,000 gp",
    meta: ["Scimitar", "Duelist", "Drow"],
    imageUrl: itemImage("Twinkle"),
  },
  {
    id: "weapon-icingdeath",
    category: "weapons",
    title: "Icingdeath",
    description: "A frost-bitten scimitar for monster hunters, dragon slayers, or winter-bound champions.",
    subtitle: "Named relic",
    rarity: "very_rare",
    value: "5,000 gp",
    meta: ["Scimitar", "Cold", "Dragon trophy"],
    imageUrl: itemImage("Icingdeath"),
  },
  {
    id: "weapon-moonblade",
    category: "weapons",
    title: "Moonblade",
    description: "An elven ancestral blade that works for dynastic politics, lineages, and ancient oaths.",
    subtitle: "Ancestral weapon",
    rarity: "legendary",
    value: "Priceless",
    meta: ["Longsword", "Elven", "Lineage"],
    imageUrl: itemImage("Moonblade"),
  },
  {
    id: "weapon-dragonlance",
    category: "weapons",
    title: "Dragonlance",
    description: "A battlefield legend for mounted charges, dragon wars, and last-stand heroic moments.",
    subtitle: "War relic",
    rarity: "legendary",
    value: "8,000 gp",
    meta: ["Lance", "Dragon war", "Heroic"],
    imageUrl: itemImage("Dragonlance"),
  },
  {
    id: "weapon-bow-elven-oath",
    category: "weapons",
    title: "Bow of the First Oath",
    description: "A famous longbow preset for ranger captains, wardens, and forest sentinel storylines.",
    subtitle: "Signature weapon",
    rarity: "rare",
    value: "2,500 gp",
    meta: ["Longbow", "Warden", "Forest relic"],
    imageUrl: itemImage("Bow of the First Oath"),
  },
  {
    id: "potion-healing-major",
    category: "potions",
    title: "Grand Healing Draught",
    description: "A premium healing potion preset for boss-fight prep, noble alchemists, or emergency caches.",
    subtitle: "Potion preset",
    rarity: "uncommon",
    value: "150 gp",
    meta: ["Healing", "Consumable", "Support"],
    featured: true,
    imageUrl: itemImage("Grand Healing Draught"),
  },
  {
    id: "potion-phoenix-tonic",
    category: "potions",
    title: "Phoenix Tonic",
    description: "A vivid revival-themed potion for fiery temples, phoenix cultists, or resurrection bargains.",
    subtitle: "Potion preset",
    rarity: "rare",
    value: "600 gp",
    meta: ["Fire", "Recovery", "Revival"],
    imageUrl: itemImage("Phoenix Tonic"),
  },
  {
    id: "armor-dragonscale",
    category: "armor",
    title: "Dragon Scale Mail",
    description: "An iconic armor choice for monster hunters, dragon heirs, or draconic champions.",
    subtitle: "Armor preset",
    rarity: "very_rare",
    value: "8,000 gp",
    meta: ["Armor", "Dragon", "Scale mail"],
    featured: true,
    imageUrl: itemImage("Dragon Scale Mail"),
  },
  {
    id: "armor-mithral-warden",
    category: "armor",
    title: "Mithral Warden Plate",
    description: "A noble defense preset for dwarven vaults, palace guards, or veteran paladins.",
    subtitle: "Armor preset",
    rarity: "rare",
    value: "4,500 gp",
    meta: ["Plate", "Mithral", "Defense"],
    imageUrl: itemImage("Mithral Warden Plate"),
  },
  {
    id: "gear-bag-holding",
    category: "gear",
    title: "Bag of Holding",
    description: "A classic expedition utility pick that instantly improves long-haul dungeon logistics.",
    subtitle: "Iconic utility",
    rarity: "uncommon",
    value: "400 gp",
    meta: ["Storage", "Travel", "Classic"],
    featured: true,
    imageUrl: itemImage("Bag of Holding"),
  },
  {
    id: "gear-immovable-rod",
    category: "gear",
    title: "Immovable Rod",
    description: "A famous trick-item for creative players, heists, lockouts, climbs, and trap solutions.",
    subtitle: "Iconic utility",
    rarity: "uncommon",
    value: "500 gp",
    meta: ["Trick tool", "Utility", "Puzzle"],
    imageUrl: itemImage("Immovable Rod"),
  },
  {
    id: "treasure-crown-emberfall",
    category: "treasure",
    title: "Crown of Emberfall",
    description: "A regal treasure card for succession arcs, imperial tombs, or political bargaining.",
    subtitle: "Treasure preset",
    rarity: "legendary",
    value: "12,000 gp",
    meta: ["Crown", "Royal", "Political"],
    featured: true,
    imageUrl: itemImage("Crown of Emberfall"),
  },
  {
    id: "treasure-pearl-depths",
    category: "treasure",
    title: "Pearl of the Tidelord",
    description: "A famous jeweled treasure suited to sea courts, drowned ruins, and leviathan tribute.",
    subtitle: "Treasure preset",
    rarity: "very_rare",
    value: "7,500 gp",
    meta: ["Pearl", "Ocean", "Relic"],
    imageUrl: itemImage("Pearl of the Tidelord"),
  },
];

export const CURATED_NPC_TEMPLATES: CuratedNpcTemplate[] = [
  {
    id: "npc-elminster",
    name: "Elminster",
    race: "Human",
    npcClass: "Wizard",
    alignment: "Chaotic Good",
    relationship: "patron",
    faction: "Harpers",
    locationName: "A hidden tower or moonlit crossroads",
    personality: "Dryly amused, impossibly well-informed, and always three plans ahead.",
    appearance: "An elderly mage in road-worn robes with sharp eyes and an unmistakable aura of power.",
    voice: "Measured, wry, and theatrical when it serves him.",
    description: "A legendary wandering archmage who can serve as mentor, manipulator, or world-shaping patron.",
    notes: "Use when the campaign needs a credible sage with enough gravitas to redirect the whole story.",
    cr: "18",
    featured: true,
    imageUrl: npcImage("Elminster"),
  },
  {
    id: "npc-drizzt",
    name: "Drizzt Do'Urden",
    race: "Drow",
    npcClass: "Ranger",
    alignment: "Chaotic Good",
    relationship: "ally",
    locationName: "Frozen wilderness, frontier roads, or the edge of a monster hunt",
    personality: "Reflective, precise, honorable, and quietly intense.",
    appearance: "A lithe dark elf with panther-like grace, travel-worn gear, and twin enchanted scimitars.",
    voice: "Calm, deliberate, and earnest.",
    description: "A renowned wandering hero, excellent as a rescue ally, rival hunter, or impossible standard to live up to.",
    notes: "Best used sparingly so the party still owns the spotlight in scenes involving him.",
    cr: "16",
    featured: true,
    imageUrl: npcImage("Drizzt Do'Urden"),
  },
  {
    id: "npc-mordenkainen",
    name: "Mordenkainen",
    race: "Human",
    npcClass: "Wizard",
    alignment: "True Neutral",
    relationship: "neutral",
    locationName: "Planar crossroads, hidden sanctum, or catastrophe site",
    personality: "Detached, analytical, and willing to intervene only when the balance breaks.",
    appearance: "An austere mage framed by immaculate sigils, layered travel leathers, and warded gear.",
    voice: "Controlled, precise, and skeptical.",
    description: "A legendary archmage suited to planar crises, cosmic balance plots, and uncomfortable truths.",
    notes: "Use as a source of hard answers, limited aid, and high-level magical perspective.",
    cr: "18",
    imageUrl: npcImage("Mordenkainen"),
  },
  {
    id: "npc-tasha",
    name: "Tasha",
    race: "Human",
    npcClass: "Wizard",
    alignment: "Chaotic Neutral",
    relationship: "rival",
    locationName: "Arcane salon, cursed theater, or reality-warped manor",
    personality: "Brilliant, irreverent, dangerous, and delighted by clever chaos.",
    appearance: "A sharply dressed archmage with predatory confidence and unnervingly amused eyes.",
    voice: "Playful, cutting, and delighted by audacity.",
    description: "A high-voltage magical wildcard for campaigns that benefit from brilliance mixed with menace.",
    notes: "Strong fit for bargains, tests, magical pranks, or morally volatile patronage.",
    cr: "17",
    imageUrl: npcImage("Tasha"),
  },
  {
    id: "npc-strahd",
    name: "Strahd von Zarovich",
    race: "Vampire",
    npcClass: "Noble Warlock",
    alignment: "Lawful Evil",
    relationship: "enemy",
    locationName: "An ancient castle, storm balcony, or candlelit dining hall",
    personality: "Cultured, obsessive, proud, and terrifyingly patient.",
    appearance: "A dark aristocrat in immaculate attire with stillness that feels predatory.",
    voice: "Low, intimate, and controlled with flashes of contempt.",
    description: "A classic gothic tyrant for dread campaigns, doomed romances, and elegant cruelty.",
    notes: "Best when framed as personally interested in the party rather than just stat-block evil.",
    isEnemy: true,
    cr: "15",
    featured: true,
    imageUrl: npcImage("Strahd von Zarovich"),
  },
  {
    id: "npc-jarlaxle",
    name: "Jarlaxle Baenre",
    race: "Drow",
    npcClass: "Rogue",
    alignment: "Chaotic Neutral",
    relationship: "rival",
    faction: "Bregan D'aerthe",
    locationName: "A lavish ship, masked gala, or back-room deal",
    personality: "Charming, theatrical, opportunistic, and almost impossible to outmaneuver socially.",
    appearance: "A flamboyantly dressed drow with a smile that always means more than it reveals.",
    voice: "Smooth, amused, and dangerously warm.",
    description: "A perfect power broker for intrigue arcs, heists, and alliances that never stay simple.",
    notes: "Excellent as ally-for-now, information broker, or smiling thief-lord.",
    cr: "14",
    imageUrl: npcImage("Jarlaxle Baenre"),
  },
  {
    id: "npc-volo",
    name: "Volo",
    race: "Human",
    npcClass: "Bard",
    alignment: "Chaotic Good",
    relationship: "ally",
    locationName: "A tavern, lecture hall, or disaster he just barely escaped",
    personality: "Verbose, enthusiastic, curious, and perpetually one step from trouble.",
    appearance: "A flamboyant scholar-traveler with ink-stained notes and a battered satchel.",
    voice: "Rapid, colorful, and convinced every detail is worth sharing.",
    description: "A lore-rich comic relief contact who can still point the party toward useful leads.",
    notes: "Great for exposition, rumors, mistaken confidence, and accidental complications.",
    cr: "3",
    imageUrl: npcImage("Volo"),
  },
  {
    id: "npc-bruenor",
    name: "Bruenor Battlehammer",
    race: "Dwarf",
    npcClass: "Fighter",
    alignment: "Lawful Good",
    relationship: "patron",
    locationName: "A forge hall, war camp, or reclaimed hold",
    personality: "Gruff, loyal, stubborn, and deeply protective of his people.",
    appearance: "A broad-shouldered dwarf king with battle-worn armor and a forge-born bearing.",
    voice: "Rough, direct, and heavy with conviction.",
    description: "A dwarven ruler template for reclamation arcs, ancestral wars, and holdfast politics.",
    notes: "Useful as a grounded authority figure with emotional ties to clan, stone, and legacy.",
    cr: "10",
    imageUrl: npcImage("Bruenor Battlehammer"),
  },
];
